version: '3'
networks:
  ljpc_mailproxygui:
services:
  proxy:
    build: ./proxy
    restart: unless-stopped
    volumes:
      - ./templates:/etc/nginx/templates
      - ./web:/var/www/html
      - ./cms:/var/www/cms
      - ${SSL_FOLDER}:/etc/nginx/ssl
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/templates
      - SSL_CERT_FILE=${SSL_CERT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
      - DOMAIN=${DOMAIN}
    ports:
      - "993:993"
      - "995:995"
      - "587:587"
      - "25:25"
      - "110:110"
      - "143:143"
      - "8080:80"
    links:
      - php
    networks:
      - ljpc_mailproxygui

  php:
    build: ./php
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html
      - ./cms:/var/www/cms
    depends_on:
      - db
    links:
      - db
    networks:
      - ljpc_mailproxygui

  db:
    build: ./db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=3h0aZvklAqkZgNmoubOfNb7p7PAID4CQ
      - MARIADB_DATABASE=database
    networks:
      - ljpc_mailproxygui